---
# Ansible playbook for a GitLab server.
#
# @todo - Install postfix `yum -y install postfix`.
#
# @author Jeff Geerling (2014).

- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - deployment
